spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.plateer.ec1.**.vo com.plateer.ec1.**.model


logging:
  level:
    jdbc:
      sqlony : off
      sqltiming : info
      resultsettable : info
      audit: off
      resultset : off
      connection: off
    org:
      springframework:
        transaction:
          interceptor: trace

payment :
  inicis :
    api-key : ItEQKi3rY7uvDS8l
    mid : INIpayTest
