spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

logging:
  level:
    jdbc:
      sqlony : off
      sqltiming : info
      resultsettable : info
      audit: off
      resultset : off
      connection: off
    org:
      springframework:
        transaction:
          interceptor: trace

